In [1]:
import numpy as np

In [2]:
x = np.genfromtxt('susy_min.csv', delimiter=',', usecols=(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18), skip_header=1)
y = np.genfromtxt('susy_min.csv', delimiter=',', usecols=(0), skip_header=1)

In [4]:
print(len(x))


100000


In [14]:
y

array([ 0.,  1.,  1., ...,  1.,  0.,  0.])

In [6]:
from sklearn.model_selection import train_test_split

In [4]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=42)

In [7]:
print(len(x_treino))
x

70000


array([[ 0.97286147,  0.65385455,  1.17622459, ...,  0.9944641 ,
         1.36781549,  0.0407145 ],
       [ 1.66797304,  0.06419062, -1.22517145, ...,  0.20535576,
         1.32189345,  0.37758401],
       [ 0.44483992, -0.13429801, -0.70997161, ...,  1.562374  ,
         1.13545442,  0.18091001],
       ..., 
       [ 0.79201961,  0.00933962, -1.37919354, ...,  0.68695176,
         1.13327086,  0.0603228 ],
       [ 0.51434743, -1.14140165, -0.44557902, ...,  1.05595863,
         0.73609942,  0.0676258 ],
       [ 0.41783157,  1.08981001,  0.27129903, ...,  0.570315  ,
         1.47785294,  0.333969  ]])

In [28]:
y_teste[0]


0.0

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6, p=2)
knn.fit(x_treino, y_treino)
labels = knn.predict(x_teste)

In [9]:
print(len(labels))
labels

30000


array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [10]:
y_teste

array([ 0.,  0.,  0., ...,  0.,  0.,  1.])

In [11]:
print(knn.score(x_teste, y_teste))

0.757433333333


In [12]:
x = np.genfromtxt('susy_min.csv', delimiter=',', usecols=(1,2,3,4,6,7,8,9,10,12,13,14,15,16,17,18), skip_header=1)
y = np.genfromtxt('susy_min.csv', delimiter=',', usecols=(0), skip_header=1)

In [35]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=42)

In [36]:
print(len(x_treino))

70000


In [39]:
knn = KNeighborsClassifier(n_neighbors=18, p=2)
knn.fit(x_treino, y_treino)
labels = knn.predict(x_teste)

In [41]:
print(len(labels))
labels

30000


array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [42]:
print(knn.score(x_teste, y_teste))

0.7695


In [14]:
z = np.genfromtxt('susy_min.csv', delimiter=',', usecols=(1,2,3,4,6,7,8,9,10,12,13,14,15,16,17,18), skip_header=1)
r = np.genfromtxt('susy_min.csv', delimiter=',', usecols=(0), skip_header=1)

In [46]:
z_treino, z_teste, r_treino, r_teste = train_test_split(z, r, test_size=0.3, random_state=42)

In [47]:
print(len(z_treino))

70000


In [55]:
knn = KNeighborsClassifier(n_neighbors=16, p=2)
knn.fit(z_treino, r_treino)
labels = knn.predict(z_teste)

In [56]:
print(len(labels))
labels

30000


array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [57]:
print(knn.score(z_teste, r_teste))

0.770866666667


In [44]:
t = np.genfromtxt('SUSY.csv', delimiter=',', usecols=(9,10,11,12,13,14,15,16,17,18), skip_footer=4000000)
v = np.genfromtxt('SUSY.csv', delimiter=',', usecols=(0), skip_footer=4000000)

In [ ]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=(.9 * (1 - .9)))
dataset_susy = sel.fit_transform(t)
dataset_susy[0,:]
t_treino, t_teste, v_treino, v_teste = train_test_split(dataset_susy, v, test_size=0.3, random_state=0)
from sklearn.neighbors import KNeighborsClassifier
for i in range(6, 19):
    knn = KNeighborsClassifier(n_neighbors=i, p=2)
    knn.fit(t_treino, v_treino)
    labels = knn.predict(t_teste)
    print("{} : {}".format(i, knn.score(t_teste, v_teste)))

6 : 0.7702
7 : 0.7731066666666667
8 : 0.7755366666666667


In [46]:
dataset_susy[0,:]

array([ 0.81006074, -0.25255212,  1.92188704,  0.88963741,  0.41077185,
        1.14562082,  1.93263209,  0.9944641 ])

In [30]:
print(len(t_treino))

700000


In [39]:
from sklearn.neighbors import KNeighborsClassifier
for i in range(1, 10):
    knn = KNeighborsClassifier(n_neighbors=i, p=2)
    knn.fit(t_treino, v_treino)
    labels = knn.predict(t_teste)
    print("{} : {}".format(i, knn.score(t_teste, v_teste)))

1 : 0.7148444444444444
2 : 0.7376333333333334
3 : 0.7500555555555556
4 : 0.7601888888888889
5 : 0.7654444444444445
6 : 0.7698666666666667
7 : 0.7727333333333334
8 : 0.7754444444444445
9 : 0.7774333333333333


In [40]:
for i in range(10, 19):
    knn = KNeighborsClassifier(n_neighbors=i, p=2)
    knn.fit(t_treino, v_treino)
    labels = knn.predict(t_teste)
    print("{} : {}".format(i, knn.score(t_teste, v_teste)))

10 : 0.7788888888888889
11 : 0.7805333333333333
12 : 0.7803222222222223
13 : 0.7817111111111111
14 : 0.7817888888888889
15 : 0.7829
16 : 0.7833222222222223
17 : 0.7838555555555555
18 : 0.7841


0.760726666667
